/*
 * Copyright (C) 2013  Bob Rutledge
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 * and open the template in the editor.
 */

package org.lreqpcr.core.data_objects;

/**
 * 
 * @author Bob Rutledge
 */
public class CalibrationDbInfo extends DatabaseInfo {
    private boolean isOcfNormalizedToFmax;

    /**
     * Normalizing the OCF generated by individual profiles to the Run's 
     * average Fmax corrects for well to well 
     * differences in the instrument optical calibration.
     * 
     * @return whether the OCF is adjusted to the Run's average Fmax 
     */
    public boolean isOcfNormalizedToFmax() {
        return isOcfNormalizedToFmax;
    }

    /**
     * Normalizing the OCF generated by individual profiles to the Run's 
     * average Fmax corrects for well to well 
     * differences in the instrument optical calibration.
     * 
     * @param isOcfNormalizedToFmax whether the OCF is normalized to the Run's Fmax
     */
    public void setIsOcfNormalizedToFmax(boolean isOcfNormalizedToFmax) {
        this.isOcfNormalizedToFmax = isOcfNormalizedToFmax;
    }
    
}
