/*
 * Copyright (C) 2013  Bob Rutledge
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 * and open the template in the editor.
 */
package org.lreqpcr.core.data_objects;

/**
 * Stores various Profile database related information. 
 *
 * @author Bob Rutledge
 * @since version 0.8.6
 */
public abstract class DatabaseInfo extends LreObject {
    private  double versionNumber;//e.g. 0.93 == 0.9.3
    private double avRunFmax;//The average Fmax derived by averageing the Run Fmax average across all of the Runs in the database
    private double avRunFmaxCV;//The CV for the average Fmax values derived from multiple Runs    

    public DatabaseInfo() {
       versionNumber = 0.93;
    }

    
    /**
     * Program version number with the last period removed (e.g. 0.93 == 0.9.3)
     * 
     * @since version 0.9.3
     * @return the version number
     */
    public double getVerionNumber() {
        return versionNumber;
    }

    /**
     * The average Fmax generated by all profiles within all Runs
     * within the database, excluding average Profiles. 
     * <p>
     * This is used 
     * to correct for well-to-well differences in fluorescence units. 
     * This was derived from the observation that some instruments 
     * calibration fluorescence for each well individually. Variance in this 
     * calibration can led to quantitative errors for both Fo and Ct 
     * based analysis (> 1 fold). 
     * 
     * @return avRunFmax the average Fmax across all runs within the database
     */
    public double getAvRunFmax() {
        return avRunFmax;
    }

    /**
     * The average Fmax generated by all profiles within all Runs
     * within the database, excluding average Profiles. This is used 
     * to correct for well-to-well differences in fluorescence units. 
     * This was derived from the observation that some instruments 
     * calibration fluorescence for each well individually. Variance in this 
     * calibration can led to quantitative errors for both Fo and Ct 
     * based analysis. 
     * 
     * @param avRunFmax the average Fmax across all runs within the database
     */
    public void setAvRunFmax(double avRunFmax) {
        this.avRunFmax = avRunFmax;
    }

    public double getAvRunFmaxCV() {
        return avRunFmaxCV;
    }

    public void setAvRunFmaxCV(double avRunFmaxCV) {
        this.avRunFmaxCV = avRunFmaxCV;
    }
}