/*
 * Copyright (C) 2010  Bob Rutledge
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 * and open the template in the editor.
 */

package org.lreqpcr.core.data_objects;

import java.util.List;

/**
 * NOTE: this interface can only be implemented by a Profile.
 * An average profile is generated by averaging, for each cycle, the Fc datasets
 * produced by technical replicates.
 * This increases Fc read precision which in turn generates a more reliable analysis. 
 * 
 *
 * @author Bob Rutledge
 */
public interface AverageProfile {

    /**
     * List of the replicate profiles from which this average profile was constructed.
     * @return List of the replicate profiles
     */
    public List<? extends Profile> getReplicateProfileList();

    /**
     * Sets the list of the replicate profiles from which this average profile was constructed.
     * @param replicateProfileList List of replicate profiles
     */
    public void setReplicateProfileList(List<? extends Profile> replicateProfileList);

    public int numberOfActiveReplicateProfiles();

    public boolean determineIfTheAverageReplicateNoIsLessThan10Molecules();

    public boolean isReplicateAverageNoLessThan10Molecules();

}
