/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.lreqpcr.ui_components;

import java.text.DecimalFormat;
import org.lreqpcr.core.data_objects.Profile;
import org.lreqpcr.core.data_processing.ProfileSummary;
import org.lreqpcr.core.utilities.FormatingUtilities;

/**
 *
 * @author brutledg
 */
public class CurveFittingParam extends javax.swing.JPanel {

    private Profile profile;
    private DecimalFormat df = new DecimalFormat();
    private DecimalFormat dfE = new DecimalFormat("0.00E0");

    /**
     * Creates new form CurveFittingParam
     */
    public CurveFittingParam() {
        initComponents();
    }

    public void updateDisplay(ProfileSummary prfSum) {
        profile = prfSum.getProfile();
        df.applyPattern("#0.00%");
        String foCV = df.format(profile.getCfFoSD() / profile.getCfFo() * 100);
        cfFoDisplay.setText(dfE.format(profile.getCfFo()) + " ±" + foCV);
        df.applyPattern("#0.00%");
        String emaxCV = df.format(profile.getCfEmaxSD() / profile.getCfEmax() * 100);
        df.applyPattern("#.0%");
        emaxDisplay.setText(df.format(profile.getCfEmax()) + " ±" + emaxCV);
        double fmax = profile.getCfFmax();
        df.applyPattern(FormatingUtilities.decimalFormatPattern(fmax));
        fmaxDisplay.setText(df.format(fmax));
        double fb = profile.getCfFb();
        df.applyPattern(FormatingUtilities.decimalFormatPattern(fb));
        fbDisplay.setText(df.format(fb));
        double fbSlope = profile.getCfFbSlope();
        df.applyPattern(FormatingUtilities.decimalFormatPattern(fbSlope));
        fbSlopeDisplay.setText(df.format(fbSlope));
    }

    void clearPanel() {
        cfFoDisplay.setText("");
        emaxDisplay.setText("");
        fmaxDisplay.setText("");
        fbDisplay.setText("");
        fbSlopeDisplay.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cfFoDisplay = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emaxDisplay = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fmaxDisplay = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fbDisplay = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fbSlopeDisplay = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CurveFittingParam.class, "CurveFittingParam.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(CurveFittingParam.class, "CurveFittingParam.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(cfFoDisplay, org.openide.util.NbBundle.getMessage(CurveFittingParam.class, "CurveFittingParam.cfFoDisplay.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(CurveFittingParam.class, "CurveFittingParam.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(emaxDisplay, org.openide.util.NbBundle.getMessage(CurveFittingParam.class, "CurveFittingParam.emaxDisplay.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(CurveFittingParam.class, "CurveFittingParam.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(fmaxDisplay, org.openide.util.NbBundle.getMessage(CurveFittingParam.class, "CurveFittingParam.fmaxDisplay.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(CurveFittingParam.class, "CurveFittingParam.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(fbDisplay, org.openide.util.NbBundle.getMessage(CurveFittingParam.class, "CurveFittingParam.fbDisplay.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(CurveFittingParam.class, "CurveFittingParam.jLabel5.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(fbSlopeDisplay, org.openide.util.NbBundle.getMessage(CurveFittingParam.class, "CurveFittingParam.fbSlopeDisplay.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cfFoDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fmaxDisplay)
                            .addComponent(emaxDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fbDisplay))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fbSlopeDisplay)))
                .addGap(0, 151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cfFoDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(emaxDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fmaxDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fbDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fbSlopeDisplay)))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cfFoDisplay;
    private javax.swing.JLabel emaxDisplay;
    private javax.swing.JLabel fbDisplay;
    private javax.swing.JLabel fbSlopeDisplay;
    private javax.swing.JLabel fmaxDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
