/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.lreqpcr.ui_components;

import java.text.DecimalFormat;
import org.lreqpcr.core.data_objects.Profile;
import org.lreqpcr.core.data_processing.ProfileSummary;
import org.lreqpcr.core.utilities.FormatingUtilities;

/**
 *
 * @author Bob Rutledge
 */
public class NonlinearRegressionParam extends javax.swing.JPanel {

    private Profile profile;
    private DecimalFormat df = new DecimalFormat();
    private DecimalFormat dfE = new DecimalFormat("0.00E0");

    /**
     * Creates new form NonlinearRegressionParam
     */
    public NonlinearRegressionParam() {
        initComponents();
    }

    public void updateDisplay(ProfileSummary prfSum) {
        profile = prfSum.getProfile();
        String CV;
        df.applyPattern("#0.0%");
        CV = df.format(profile.getNrFoSD() / profile.getNrFo() * 100);
        nrFoDisplay.setText(dfE.format(profile.getNrFo()) + " ±" + CV);
        CV = df.format(profile.getNrEmaxSD() / profile.getNrEmax() * 100);
        nrEmaxDisplay.setText(df.format(profile.getNrEmax()) + " ±" + CV);
        df.applyPattern("#0.0%");
        CV = df.format(profile.getNrFmaxSD() / profile.getNrFmax() * 100);
        df.applyPattern(FormatingUtilities.decimalFormatPattern(profile.getNrFmax())); 
        nrFmaxDisplay.setText(df.format(profile.getNrFmax()) + " ±" + CV);
        df.applyPattern("#0.0%");
        CV = df.format(profile.getNrFbSD() / profile.getNrFb() * 100);
        double fb = profile.getNrFb();
        df.applyPattern(FormatingUtilities.decimalFormatPattern(fb));
        nrFbDisplay.setText((df.format(profile.getNrFb()) + " ±" + CV));
        df.applyPattern("#0.0%");
        CV = df.format(profile.getNrFbSlopeSD() / profile.getNrFbSlope()* 100);
        df.applyPattern(FormatingUtilities.decimalFormatPattern(profile.getNrFbSlope()));
        nrFbSlopeDisplay.setText(df.format(profile.getNrFbSlope()) + " ±" + CV);
    }

    void clearPanel() {
        nrFoDisplay.setText("");
        nrEmaxDisplay.setText("");
        nrFmaxDisplay.setText("");
        nrFbDisplay.setText("");
        nrFbSlopeDisplay.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nrFoDisplay = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nrEmaxDisplay = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nrFmaxDisplay = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nrFbDisplay = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nrFbSlopeDisplay = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(NonlinearRegressionParam.class, "NonlinearRegressionParam.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(NonlinearRegressionParam.class, "NonlinearRegressionParam.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(nrFoDisplay, org.openide.util.NbBundle.getMessage(NonlinearRegressionParam.class, "NonlinearRegressionParam.nrFoDisplay.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(NonlinearRegressionParam.class, "NonlinearRegressionParam.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(nrEmaxDisplay, org.openide.util.NbBundle.getMessage(NonlinearRegressionParam.class, "NonlinearRegressionParam.nrEmaxDisplay.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(NonlinearRegressionParam.class, "NonlinearRegressionParam.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(nrFmaxDisplay, org.openide.util.NbBundle.getMessage(NonlinearRegressionParam.class, "NonlinearRegressionParam.nrFmaxDisplay.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(NonlinearRegressionParam.class, "NonlinearRegressionParam.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(nrFbDisplay, org.openide.util.NbBundle.getMessage(NonlinearRegressionParam.class, "NonlinearRegressionParam.nrFbDisplay.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(NonlinearRegressionParam.class, "NonlinearRegressionParam.jLabel5.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(nrFbSlopeDisplay, org.openide.util.NbBundle.getMessage(NonlinearRegressionParam.class, "NonlinearRegressionParam.nrFbSlopeDisplay.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nrFoDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nrFmaxDisplay)
                            .addComponent(nrEmaxDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nrFbDisplay))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nrFbSlopeDisplay)))
                .addGap(0, 151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nrEmaxDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nrFoDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nrFmaxDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nrFbDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nrFbSlopeDisplay))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel nrEmaxDisplay;
    private javax.swing.JLabel nrFbDisplay;
    private javax.swing.JLabel nrFbSlopeDisplay;
    private javax.swing.JLabel nrFmaxDisplay;
    private javax.swing.JLabel nrFoDisplay;
    // End of variables declaration//GEN-END:variables
}
